### ISSUE TITLE
Environment variable to override logger level in config and change to env name prefix

### ISSUE THREAD

**Issue by mauvilsa** [omni-us/reconplogger#3]
@nischalhp yesterday in a meeting on code standardization we briefly talked about the logger level. Using reconplogger allows the logger to be overridden from outside, e.g. via helm, so the code should not override the logger level. However, currently the only way in reconplogger to change the logger level is to feed through the config environment variable, a complete config with the desired log level, which seems cumbersome. So it could be good to have an additional environment variable that if set overrides the logger's level.

Related to this, having a third environment variable makes it a bit redundant to give the names of three environment variables. Instead, what could be given is a prefix for the environment variable names. So, for instance a `prefix=MYLOGGER` could be given which would imply that the following three environment variables would be checked: `MYLOGGER_CFG`, `MYLOGGER_NAME` and `MYLOGGER_LEVEL`.

**Comment by nischalhp** [comment]
This issue has been resolved with this commit : https://github.com/omni-us/reconplogger/commit/a6ab1bb0b36e1a199506832a4047c539da069d35

**Comment by mauvilsa** [comment]
The commit only resolved the env prefix, not the logging level. I have created pull request https://github.com/omni-us/reconplogger/pull/5 that would resolve this part.
